### ISSUE TITLE
In folder "javascript" there are links only

### ISSUE THREAD

**Issue by rudi48** [jeffeb3/YunThermostat#2]
Hello jeffeb3,
I tried to use your very interesting software.
Unfortunately in folder  "javascript" there are links only.
Which version of the libraries did you use?
Regards, Rudolf

**Comment by jeffeb3** [comment]
Rudolf,

I hope you like it. These are the versions I'm using:
jquery: 1.7.2
jquery-mobile: 1.4.5
jquery-flot: 0.8.3

I'll update the docs to include this information.

**Comment by jeffeb3** [comment]
pushed.

Also, if you make any changes, please fork the project. I'd be interested in what other might do with it.

**Comment by rudi48** [comment]
Hello jeffeb3,
Thank you very much for explaining that.
Unfortunately also the files updater.js and forms.js are missing, which are called in web.py,
line 188 and 191. 
I try to understand your very interesting program, especially the updating procedure.
Therefore it would be nice if you could provide also these files.
Thank you.

Regards, Rudolf

**Comment by jeffeb3** [comment]
Those files get created on the fly. The start as tpl files in the view folder, then bottle replaces parts of it with python variables. 

so update.tpl is in view and forms.tpl are in view. The {{variable}} and % CODE are the parts that get replaced. See http://bottlepy.org/docs/dev/stpl.html

**Comment by jeffeb3** [comment]
Alright, I thought about it and I think I'm OK with including the source for jquery, etc. 

I originally didn't want to. Partly because it's a waste of resources (having someone else's source in my repo means more copies of the source) and partly because I think those projects are great, and people should go to them to get the source. But, it is kind of difficult to get started without them. Also, partly because I didn't even bother to look to see which license they were using, but it's MIT, so I think I'm OK.

**Comment by rudi48** [comment]
Hello jeffeb3,
Thank you very much for your explanations,
The {{variable}} syntax I have already recognized, but the single Python statement:
    var % = JSON.parse(e.data);
I was not aware of. I assumed the template is pure Javascript.

My project is, to port a tkinter GUI to Android, as a web GUI, please see;
http://www.rudiswiki.de/wiki9/ArduinoLabPSU2#Remote_control
together with the ESP8266 WiFi interface.
In Android there is no tkinter available, but Python.
Once it has a web GUI, it can be used anywhere.
I can also think of a Python server in my local network, and just use the web browser
in Android.

Regards, Rudolf

**Comment by jeffeb3** [comment]
Looks like a neat project.

If you had a python server running, it could read from the arduino using
telnet and provide the web interface much like my project does. In that
case, jquery, bottle, and for are useful tools. Take a look at this
(simpler) project:

https <https://learn.adafruit.com/smart-measuring-cup/overview>://
<https://learn.adafruit.com/smart-measuring-cup/overview>learn.adafruit.com
<https://learn.adafruit.com/smart-measuring-cup/overview>/
<https://learn.adafruit.com/smart-measuring-cup/overview>smart-
<https://learn.adafruit.com/smart-measuring-cup/overview>measuring-cup
<https://learn.adafruit.com/smart-measuring-cup/overview>/overview
<https://learn.adafruit.com/smart-measuring-cup/overview>

The yun has enough processing to run python, launch 20 threads, and handle
my webpage. I'm not sure the arduino does, so there would be some
sacrifices. But you can actually provide a web interface from the esp8266.
You could store the index.html, updater.js, etc on the Internet somewhere,
and just the EventSource would be pointing at the arduino/esp8266. The
Server Side Events are a pretty simple protocol. The esp8266 would still
have to handle requests, which is what you would use to control things.

In your web page. The sliders look cool, but they are hard to control on a
touch screen. Text inputs are much easier to use.

Have fun!
